### ISSUE TITLE
Add an automated build to Docker Hub or Quay

### ISSUE THREAD

**Issue by whereisaaron** [mintel/dex-k8s-authenticator#10]
It would be nice to provide a reference build of the `dex-k8s-authenticator` container image somewhere.

I have made an automated build of my fork. You could do the same thing for this repo instead.
https://hub.docker.com/r/whereisaaron/dex-k8s-authenticator/

We should also start make SemVer releases, so e.g. apply a 'v0.1' tag and get Docker Hub to build each SemVer tag.

**Comment by nabadger** [comment]
I'll take a look at this.

**Comment by nabadger** [comment]
@whereisaaron I've setup and linked this repo on dockerhub, merged in PR #9 and created a v0.1.0 tag.

I've also updated the chart readme and values.yml to point at the mintel repo on dockerhub.

Thanks again.
