### ISSUE TITLE
Can the latest image be tagged with a version?

### ISSUE THREAD

**Issue by krishnadurai** [mintel/dex-k8s-authenticator#102]
Looks like that the last image to be tagged with a version was 1.1.0. This was 8 months ago.

Refer https://hub.docker.com/r/mintel/dex-k8s-authenticator/tags

Can we have a newer release?

**Comment by nabadger** [comment]
Will do - just preparing a release. Will probably create the tag/image tomorrow.

**Comment by krishnadurai** [comment]
@nabadger Thanks.

**Comment by nabadger** [comment]
@krishnadurai there's a v1.2.0 release now (image on dockerhub as well).
