### ISSUE TITLE
Default value of caCerts.secrets in dex-k8s-authenticator chart should be a list instead of a map

### ISSUE THREAD

**Issue by tsoontornwutikul** [mintel/dex-k8s-authenticator#104]
In `charts/dex-k8s-authenticator/values.yaml`, the default value of `caCerts.secrets` should be an empty list (`[]`) instead of an empty map (`{}`) to be consistent with the documentation and to avoid merge failure when custom values are provided.

https://github.com/mintel/dex-k8s-authenticator/blob/2e3c987018b3487cc83d410b35cc0a4d00de19ca/charts/dex-k8s-authenticator/values.yaml#L69

**Comment by nabadger** [comment]
Thanks @tsoontornwutikul - I've updated this now.
