### ISSUE TITLE
please create github releases

### ISSUE THREAD

**Issue by k0da** [mintel/dex-k8s-authenticator#108]
We use github releases to query upstream whether new release is our and pull a version info from a release.

So far nothing can be queried:
```
curl https://api.github.com/repos/mintel/dex-k8s-authenticator/releases
[

]
```

**Comment by nabadger** [comment]
@k0da sure thing

https://github.com/mintel/dex-k8s-authenticator/releases/tag/v1.2.0

I've added a github-release for the latest tag which the github api now returns.

We can do this going forwards no problem - is it worth back-porting the old releases for you?

**Comment by k0da** [comment]
Thanks, latest is more than enough

**Comment by k0da** [comment]
Fixed
