### ISSUE TITLE
Can this work against OpenAM based oidc?

### ISSUE THREAD

**Issue by bjethwan** [mintel/dex-k8s-authenticator#144]
Can this work against OpenAM based oidc?

**Comment by nabadger** [comment]
@bjethwan This isn't something I'm familiar with, so can't give you a definitive answer I'm afraid.

**Comment by nabadger** [comment]
It looks like you got most of this working in #145

**Comment by bjethwan** [comment]
@nabadger 
dex-k8s-authenticator works perfectly fine with OpenAM.
The deployment was smooth, as I transitioned from Dex in my personal environment to OpenAM in my org.
