### ISSUE TITLE
Get Docker version numbers without the 'v'

### ISSUE THREAD

**Issue by whereisaaron** [mintel/dex-k8s-authenticator#15]
Docker image version numbers conventionally don't have any prefix, like 'v' or 'v.' or 'ver'. But Github versions usually do have a 'v'. You can do both by having the 'v' in GitHub and using this pattern in Docker hub.

![image](https://user-images.githubusercontent.com/1109585/36384342-f66b8030-155c-11e8-9a46-e0c32186fa53.png)

**Comment by nabadger** [comment]
I've updated this on dockerhub. @whereisaaron I'll create a v0.2.0 tag soon which will include the helm chart options.
