### ISSUE TITLE
When is the next release? Badly looking for scope option to login without mail attribute

### ISSUE THREAD

**Issue by Adithimurthi** [mintel/dex-k8s-authenticator#151]
When is the next release? I am looking for scope option. So that i can use it for service accounts without mail address. Right now, i am getting below error if i login with ldap id without email address.

Login error: ldap: entry "useraccount" missing following required attribute(s): ["mail"]

**Comment by nabadger** [comment]
I just released `v1.3.0` which provides the `scopes` option.

Let me know if it works - apologies for slow releases lately, not much time on this project :)

**Comment by nabadger** [comment]
Just releasing `v1.4.0` as well, since `dexidp` released a security patch that we should all upgrade to (at least if those using SAML).
