### ISSUE TITLE
Consider drop-downs for selecting a cluster

### ISSUE THREAD

**Issue by nabadger** [mintel/dex-k8s-authenticator#2]
< 5 clusters is fine in the current interface, but what if you have a lot more...the current UI would make it annoying.

**Comment by whereisaaron** [comment]
This is probably possible, just via the go template.

Might need JavaScript if you want to display the 'Long Description' after choosing from the drop-down, and before hitting the 'Login' button.

**Comment by nabadger** [comment]
There's no real push for this yet - I'll close it for now.
