### ISSUE TITLE
Token page: supply 'certificate-authority-data' base64 encoded CA as an option to the 'certificate-authority' CA file

### ISSUE THREAD

**Issue by MnrGreg** [mintel/dex-k8s-authenticator#25]
Being able to supply the base64 encoded K8s API CA in the config.yaml and Helm values would negate the need for hosting the CA file on we separate web service.

For example not only:
k8s_ca_uri
but also a second option:
k8s_ca_cert

- Means one can skip the first Token page step altogether "Copy Kubernetes CA certificate".
- Also windows clients don't need curl.

**Comment by MnrGreg** [comment]
It seems one can't set the 'certificate-authority-data' directly with kubectl config. Instead one needs to provide the ca file location and specify --embed-certs which then populates the certificate-authority-data field in the config file. This will not achieve the desired result. Closing the issuing.

**Comment by nabadger** [comment]
@MnrGreg Regarding Windows clients - how are you downloading the CA file into the desired location?

There's a related case #8 which asks for Windows client improvements.

**Comment by MnrGreg** [comment]
With the k8s_ca_pem option one gets around the curl requirement. Not sure about 'cat' though. Perhaps one could look at using 'type' or 'echo'. Not sure how the line breaks will get handled.

I've seen options such as the below but this would require some work in the html.
(echo Here is my first line
echo Here is my second line
echo Here is my third line) > "my-new-pem-file.pem"

**Comment by nabadger** [comment]
I think we'll end up re-working the html template to support Windows in a more general fashion. The current suggested idea is to have tabs per OS (where required)...and then each tab can have OS specific instructions.

**Comment by jicowan** [comment]
@MnrGreg Is there a way to statically configure the client-certificate-data so that it gets added to the kubeconfig or do you have to pass it a URI?
