### ISSUE TITLE
Error: apiVersion "apps/v1beta2" in dex/templates/deployment.yaml is not available

### ISSUE THREAD

**Issue by kostyrev** [mintel/dex-k8s-authenticator#37]
Is v1beta2 really necessary?

**Comment by nabadger** [comment]
So  apps/v1beta2 for 1.8 clusters and apps/v1 for 1.9 clusters.

It really depends what version of the k8s people are running right?

There doesn't seem to be any real consistency on how charts are developed (from what I can tell). I'm guessing people fork charts and update as required to suit their own cluster. Ideally a chart maintainer would support the latest stable - but k8s moves fast, so I suspect a lot of people are still running k8s 1.7 ;)

We can make the apiVersion a value override as per #13 ...but that won't always be enough - would it fix your specific issue?

**Comment by nabadger** [comment]
Fixed as per  #44 

Thanks again.
