### ISSUE TITLE
Add copy-to-clipboard option for selecting kubectl config commands

### ISSUE THREAD

**Issue by nabadger** [mintel/dex-k8s-authenticator#4]
If you're using multipel clients (i.e. different laptops to connect to the same cluster), then your'll need to generate a new re-fresh token each time (unless you have some centralized store)

It's easy to incorrectly copy the credentials (mostly because they go off the page).

**Comment by whereisaaron** [comment]
My PR #5 stops them going off the page, without 'breaking' the line, so they still copy and paste as a single long line.

**Comment by MnrGreg** [comment]
PR #32 enables copy-to-clipboard.

We now need to work through the cli command alternatives for windows. e.g. cater for curl, cat EOF and true functionality.

Also referenced in #8

**Comment by nabadger** [comment]
This is now merged to master and there's some improvements in the feat-multi-os-support branch (to be merged soon).
