### ISSUE TITLE
dex-k8s-authenticator Helm chart image issue

### ISSUE THREAD

**Issue by praveendhac** [mintel/dex-k8s-authenticator#47]
dex-k8s-authenticator helm chart user below Docker image
```
image:
  repository: mintel/dex-k8s-authenticator
  tag: latest
  pullPolicy: Always
```
But when the helm chart is deployed the container never comes up, error `CrashLoopBackOff ` 
```
# deployed helm using
$ helm upgrade --install --namespace dex-server-ns --values dex-k8s-authenticator-dex-server.yaml dex-server-app-helm charts/dex
$ kubectl get all -n dex-server-ns
NAME                                      READY     STATUS             RESTARTS   AGE
pod/dex-server-app-helm-dd68bcc69-9l7w9   0/1       CrashLoopBackOff   8          20m
```

Error
```
oci runtime error: container_linux.go:265: starting container process caused "exec: \"/usr/local/bin/dex\": stat /usr/local/bin/dex: no such file or directory"
```

Full events
```
Events:
  Type     Reason                 Age                 From                                                               Message
  ----     ------                 ----                ----                                                               -------
# Default values for dex-k8s-authenticator.
  Normal   Scheduled              20m                 default-scheduler                                                  Successfully assigned dex-server-app-helm-dd68bcc69-9l7w9 to dex-server-cpu-worker-7f765cf5dd-tcnjp
  Normal   SuccessfulMountVolume  20m                 kubelet, dex-server-cpu-worker-7f765cf5dd-tcnjp  MountVolume.SetUp succeeded for volume "config"
  Normal   SuccessfulMountVolume  20m                 kubelet, dex-server-cpu-worker-7f765cf5dd-tcnjp  MountVolume.SetUp succeeded for volume "dex-server-app-helm-token-64sgl"
  Normal   Pulling                19m (x4 over 20m)   kubelet, dex-server-cpu-worker-7f765cf5dd-tcnjp  pulling image "mintel/dex-k8s-authenticator:latest"
  Normal   Pulled                 19m (x4 over 20m)   kubelet, dex-server-cpu-worker-7f765cf5dd-tcnjp  Successfully pulled image "mintel/dex-k8s-authenticator:latest"
  Normal   Created                19m (x4 over 20m)   kubelet, dex-server-cpu-worker-7f765cf5dd-tcnjp  Created container
  Warning  Failed                 19m (x4 over 20m)   kubelet, dex-server-cpu-worker-7f765cf5dd-tcnjp  Error: failed to start container "dex": Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/usr/local/bin/dex\": stat /usr/local/bin/dex: no such file or directory"
  Warning  BackOff                31s (x95 over 20m)  kubelet, dex-server-cpu-worker-7f765cf5dd-tcnjp  Back-off restarting failed container
```

**Comment by nabadger** [comment]
Looking at this now

**Comment by nabadger** [comment]
@praveendhac It looks like you're deploying the Dex chart with the dex-k8s-authenticator values (they are 2 independent charts)

I think you should be using:

```
helm upgrade \
 --install 
 --namespace <dex-k8s-auth-ns>
 --values <dex-k8s-auth-values.yaml> charts/dex-k8s-authenticator
```
.

Let me know if this makes sense and fixes the issue for you.

**Comment by praveendhac** [comment]
dex-server-ns is the namespace where Dex is deployed so deploying dex-k8s-authenticator- in the same namespace.

Helm deployment command used
```
helm upgrade --install --namespace dex-server-ns --values dex-k8s-authenticator-dex-server.yaml dex-server-app-helm charts/dex-k8s-authenticator```

Pod Status and Events
```
$ kubectl get all -n dex-server-ns
NAME                                                             READY     STATUS             RESTARTS   AGE
pod/dex-server-app-helm-dex-k8s-authenticator-69d456968c-b4d2p   0/1       CrashLoopBackOff   3          1m

Events:
  Type     Reason     Age               From                                                              Message
  ----     ------     ----              ----                                                              -------
  Normal   Scheduled  1m                default-scheduler                                                 Successfully assigned dex-server-ns/dex-server-app-helm-dex-k8s-authenticator-69d456968c-b4d2p to shoot--msa-infra--dex-server-cpu-worker-b5f659cc4-r24ld
  Normal   Pulled     8s (x5 over 1m)   kubelet, shoot--msa-infra--dex-server-cpu-worker-b5f659cc4-r24ld  Container image "quay.io/coreos/dex:v2.9.0" already present on machine
  Normal   Created    8s (x5 over 1m)   kubelet, shoot--msa-infra--dex-server-cpu-worker-b5f659cc4-r24ld  Created container
  Normal   Started    8s (x5 over 1m)   kubelet, shoot--msa-infra--dex-server-cpu-worker-b5f659cc4-r24ld  Started container
  Warning  BackOff    7s (x10 over 1m)  kubelet, shoot--msa-infra--dex-server-cpu-worker-b5f659cc4-r24ld  Back-off restarting failed container
```

**Comment by nabadger** [comment]
@praveendhac can you show the output of `kubectl describe pod <pod>.` and `kubectl logs <pod>` for the dex-client-app here?

**Comment by nabadger** [comment]
Ok, so if dex-k8s-authenticator cannot contact the the dex-server, it will crash on startup - there's an outstanding issue to resolve this, but it's not actually a problem since kubernetes will retry anyway.

The key issue here is that the pod cannot contact the dex-server instance.

It looks like it can't talk to `https://dex-server-cpu-worker-b5f659cc4-r24ld:10250`

It should be contacting it via the ingress.

I'm really not sure why it's actually pointing at:

`https://dex-server-cpu-worker-b5f659cc4-r24ld:10250/containerLogs/dex-server-ns/dex-client-app-helm-dex-k8s-authenticator-6dfd8f6ddf-rvcjc/dex-k8s-authenticator`

This to me looks like your dex-k8s-authenticator config is wrong.

dex-k8s-authenticator will use the `issuer` field in it's config and attempt to contact that host over http.

Can you confirm what the `issuer` field is set to - from your other case, it looks like the `issuer` should be set to `https://dex.ingress.dex-server.example.com`

You can confirm this by checking the `configmap`.

**Comment by nabadger** [comment]
What if you create a busybox instance (same namespace) and try to `wget` or `curl` https://dex.ingress.dex-server.example.com/healthz 

Another way is to modify the dex-k8s-authenticator yaml and override the `cmd` and `args` option:

```
command: ["/bin/sh"]
args: ["-c", "while true; do sleep 1000;done"]
```

This will run a pod using the dex-k8s-auth image, but let you exec into it and debug it further.

**Comment by trinitronx** [comment]
@praveendhac :  Looks like same behavior when `Ingress` DNS records for `dex.example.com` don't exist or are not connectable as described by @nabadger

You'll probably see errors like the following If you can get logs out of last crashed pod.  Looks like your `kubectl logs [...SNIP...]` command is not able to access logs on the old pod because it's already gone!   You might have luck getting logs out if it's in `CrashLoopBackoff` with old pods that stick around longer rather than in fast `CrashLoop` state.  Also if you installed a log shipper to ElasticSearch or some similar log aggregation service you could find the logs there.

Here's what you _might_ see:

```
$ kubectl -n kube-system logs login-dex-k8s-authenticator-76c8dd6488-94gqt
            '/certs/ca-cert2/..2018_07_12_17_29_20.747868164/ca-cert2' -> '/usr/local/share/ca-certificates/ca-cert2.crt'
            '/certs/ca-cert1/..2018_07_12_17_29_20.735577337/ca-cert1' -> '/usr/local/share/ca-certificates/ca-cert1.crt'
            WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
            2018/07/12 22:12:27 Using config file:%!(EXTRA string=/app/config.yaml)
            2018/07/12 22:12:28 Creating new provider https://dex.kops-ldap.prod.local.foo
            2018/07/12 22:12:28 Failed to query provider "https://dex.kops-ldap.prod.local.foo": Get https://dex.kops-ldap.prod.local.foo/.well-known/openid-configuration: dial tcp: lookup dex.kops-ldap.prod.local.foo on 100.64.0.10:53: no such host
```

**Comment by nabadger** [comment]
It might just be that Dex itself isn't running:

The command you pasted above shows:

```
kubectl get all -n dex-server-ns
NAME                                                             READY     STATUS             RESTARTS   AGE
pod/dex-client-app-helm-dex-k8s-authenticator-6dfd8f6ddf-rvcjc   0/1       CrashLoopBackOff   159        13h
```

I believe you were intending to run Dex in the same namespace - if so, then you should expect to see Dex running in this above command (unless you stripped out that output)

**Comment by praveendhac** [comment]
Output of kubectl get all -n dex-server-ns has pods for dex and authenticator, deployments, services etc., just pasted dex-authenticator output to reduce unnecessary verbosity.

**Comment by nabadger** [comment]
This still looks like a networking / routing / dns / ingress issue to me.

Are you running a NetworkPolicy or a service-mesh? 

The easiest way of debugging this that I've found is per https://github.com/mintel/dex-k8s-authenticator/issues/47#issuecomment-404836681

If you modify the deployment to not run dex-k8s-auth on start, that will let you `exec` into the pod. From there you can debug network connectivity issues, plus you can see the actual configuration that is in use, and you can actually run the command by hand to confirm what happens.

Or just run another Pod with `dnsutils` and similar installed to debug this (it doesn't have to be dex-k8s-auth).

I've had similar issues before (not on dex) related to DNS and accessing hosts

**Comment by praveendhac** [comment]
I think there is domain name mismatch error in Dex Authenticator Pod.

```
/app# bin/dex-k8s-authenticator --config config.yaml --debug
2018/07/16 11:51:51 Using config file:%!(EXTRA string=/app/config.yaml)
2018/07/16 11:51:51 Creating new provider https://dex.ingress.example.com
2018/07/16 11:51:51 GET /.well-known/openid-configuration HTTP/1.1
Host: dex.ingress.example.com

2018/07/16 11:51:51 Failed to query provider "https://dex.ingress.example.com": Get https://dex.ingress.example.com/.well-known/openid-configuration: x509: certificate is valid for ingress.local, not dex.ingress.example.com
/app # command terminated with exit code 137
```
Can I use below config to bringup Dex Server with custom certificates.
```
web:
  http: 0.0.0.0:5556
  # Uncomment for HTTPS options.
  # https: 127.0.0.1:5554
  tlsCert: /etc/dex/tls.crt
  tlsKey: /etc/dex/tls.key
```

**Comment by praveendhac** [comment]
Also figured out, self-signed certificates will not work.
```
2018/07/16 14:00:08 Failed to query provider "https://dex.ingress.example.com": Get https://dex.ingress.example.com/.well-known/openid-configuration: x509: certificate signed by unknown authority
/app # command terminated with exit code 137
```

**Comment by nabadger** [comment]
@praveendhac @trinitronx 

You can add certs in the dex-k8s-authenticator helm chart (see `values.yaml`), but we think we've identified a recent bug.

There's an open case #42 which suggests a bug in how the certs are mounted in dex-k8s-authenticator helm chart. I believe there's a quick fix suggested here https://github.com/mintel/dex-k8s-authenticator/issues/42#issuecomment-403298226

If that works, I can merge that change, and you should be ok (maybe you can test the fix?)

There's a related issue here: https://github.com/mintel/dex-k8s-authenticator/issues/35

Regarding adding certs on the Dex chart, there's an open case to add that function here: https://github.com/mintel/dex-k8s-authenticator/issues/22

**Comment by praveendhac** [comment]
@nabadger 
I followed below steps which worked for me.
Create Certs (used lets encrypt as self-signed certs are not working)
```
$ certbot certonly --manual -d *.ingress.dex-appser.praveen.com --work-dir=le_wd --config-dir=le_cd --logs-dir=le_ld
$ kubectl create secret tls pd-custom-certs --key ingress.dex-appser.praveen.com.key --cert ingress.dex-appser.praveen.com.crt -n dex-appser-ns
```
Modify ingress for Dex Server and Dex Authenticator as shown below
```
----SNIP(Server)----
ingress:
  enabled: true
  path: /
  hosts:
    - dex.ingress.dex-appser.praveen.com
  tls:
    - hosts:
      - dex.ingress.dex-appser.praveen.com
      secretName: pd-custom-certs

----SNIP(Authenticator)----
ingress:
  enabled: true
  path: /
  hosts:
    - login.ingress.dex-appser.praveen.com
  tls:
    - secretName: pd-custom-certs
      hosts:
        - login.ingress.dex-appser.praveen.com
```

**Comment by nabadger** [comment]
@praveendhac  great - glad you got it working.

I'll close this for now, but will prioritise a few things

1 - documentation
2 - fixing dex-k8s-auth helm chart for self-signed certs
3 - updating dex helm chart for self-signed certs
