### ISSUE TITLE
kubectl command include IDP cert argument, even if no IDP cert is specified

### ISSUE THREAD

**Issue by whereisaaron** [mintel/dex-k8s-authenticator#6]
I offer PR #5 to fix one small bug and slightly improve the HTML of the `kubeconfig`  HTML template

1. Only include IDP certificate in kubectl if one is specified
2. Add short description of result page title
3. Tweak CSS styles (for wrapping) and HTML templates (for language)

**Comment by nabadger** [comment]
Thanks for this - I've merged it 👍
