### ISSUE TITLE
make "charts" a helm/helmsman repo

### ISSUE THREAD

**Issue by praveendhac** [mintel/dex-k8s-authenticator#70]
The charts cannot be directly used with helm/helmsman. Need to make the charts directory a helm repo.

*config1
```
helmRepos:
  dex-k8s-authenticator: "https://github.com/mintel/dex-k8s-authenticator/tree/master/charts"
Error:
2018/09/05 13:59:34 ERROR: while adding repo [dex]: Error: Looks like "https://github.com/mintel/dex-k8s-authenticator/tree/master/charts" is not a valid chart repository or cannot be reached: Failed to fetch https://github.com/mintel/dex-k8s-authenticator/tree/master/charts/index.yaml : 404 Not Found
```
*config2
```
helmRepos:
  dex-k8s-authenticator: "https://github.com/mintel/dex-k8s-authenticator"
Error:
2018/09/05 14:00:17 ERROR: while adding repo [dex]: Error: Looks like "https://github.com/mintel/dex-k8s-authenticator" is not a valid chart repository or cannot be reached: Failed to fetch https://github.com/mintel/dex-k8s-authenticator/index.yaml : 404 Not Found
```

**Comment by nabadger** [comment]
@praveendhac Do you have this working for any other Git repos? It looks like to me like it's meant to point to a charts repo, such as https://github.com/helm/chartmuseum

If not, try `https://github.com/mintel/dex-k8s-authenticator/tree/master/charts/dex-k8s-authenticator` as the URL.

**Comment by praveendhac** [comment]
The URL does not follow chart repository structure, 
https://github.com/helm/helm/blob/master/docs/chart_repository.md

```
ERROR: while adding repo [dex]: Error: Looks like "https://github.com/mintel/dex-k8s-authenticator/tree/master/charts/dex-k8s-authenticator" is not a valid chart repository or cannot be reached: Failed to fetch https://github.com/mintel/dex-k8s-authenticator/tree/master/charts/dex-k8s-authenticator/index.yaml : 404 Not Found
```

**Comment by nabadger** [comment]
That is for if you want to host your own charts repository - it's basically a collection of charts packaged up with an `index.html` that you can browse/download via the web. 

It's not a structure you would apply to a single chart.

**Comment by praveendhac** [comment]
Because of the missing index.yaml file, the repo cannot be used by helmsman. Has to convert the repo into helm repo and push to our local repo to use dex-k8s-authenticator/dex charts.

**Comment by nabadger** [comment]
@praveendhac I understand, but as far I know this is not common practise.

The `index.yaml` links to the helm packages that are pre-built `(tar.gz`). It's not common practise to add pre-built packages to Git right? These tend to live in a dedicated helm repo.

**Comment by nabadger** [comment]
Note, if this is works, I'll probably add a `mintel/charts` repo so that any charts we develop and opensource can be available (rather than having the repo under `mintel/dex-k8s-authenticator`

**Comment by nabadger** [comment]
Closing due to inactively.
