### ISSUE TITLE
Add Windows commands to kubeconfig screen

### ISSUE THREAD

**Issue by whereisaaron** [mintel/dex-k8s-authenticator#8]
I'd like to extend the kubeconfig template to document, not just Linux/Mac shell commands, but also Powershell commands for Windows. Will need to use either use one line commands, or use the back-tick continuation for Powershell. `$HOME` works for both. Could add `cmd.exe` commands also I guess.

I'd also like to include download links for the appropriate `kubectl` / `kubectl.exe`

I'd like it to be a tabbed display in the HTML template, is a small clean and optional Javascript library can be used.

**Comment by nabadger** [comment]
Perhaps we can do this by defining placeholders for each section, providing defaults, but also letting the user supply their own templates to customize the output if required. The path to kubectl could probably be provided / overridden by the configuration file.

The current sections of the page can probably be divided into the following sections:

- Cert Configuration
- Token Validation (show groups etc)
- Kubeconfig configuration
- Resources / Download links

Would these make sense as the headings for each tab?

**Comment by whereisaaron** [comment]
I was thinking a tab for each OS. Since the kubectl download and commands are different for every OS (with some overlap for Mac/Linux). Token validation is in common though, and could come first. (I'd like to extract and format the email address and group list.). Each user only needs one OS tab (at a time), and on selecting that OS tab can see everything they need in one screen.

- Token Validation
- Linux
  - kubectl download
  - Cert download
  - Kubeconfig configuration
- Mac
  - kubectl download
  - Cert download
  - Kubeconfig configuration
- Windows
  - kubectl download
  - Cert download
  - Kubeconfig configuration

I think it ok to stick with a go template and let users override that template, e.g. using a configmap mapped over the file.

**Comment by nabadger** [comment]
Ok, this makes sense :)

**Comment by nabadger** [comment]
A howto on tabs: https://www.w3schools.com/howto/howto_js_tabs.asp

As part of this, we should also:

* For Linux/Mac, re-add the '\\' esc char to allow us to continue the command onto the next line (makes it easier to read)
* Look into the alt attribute tag on the copy-to-clipboard buttons as it stops us from be able to copy/paste everything in one go (that's still useful - I'm not sure how easy it will be to add a single copy-all button...will check).

**Comment by whereisaaron** [comment]
A link to the official instructions is great. However for some clusters will need a specific version of `kubectl`. So how about rather that `curl` instructions, we provide just two links on the per-OS page:

1. A link to the official install instructions (or a configurable override URL, e.g. to a company Intranet page)
2. A download link to the appropriate Linux/Mac/Windows binary on the official build archive, with a configurable X.Y.Z version e.g.
`https://storage.googleapis.com/kubernetes-release/release/vX.Y.Z/bin/linux/amd64/kubectl`. If no version is configured, just don't display this link.

**Comment by whereisaaron** [comment]
For PowerShell the c[ontinuation character is backquote](https://stackoverflow.com/questions/3235850/how-to-enter-a-multi-line-command), *but* there must be no whitespace after the backtick (on that line) or it won't work.

For `cmd.exe` the [continuation character is caret (^)](https://stackoverflow.com/questions/69068/long-commands-split-over-multiple-lines-in-windows-vista-batch-bat-file), *but* the following newline is removed, so you must have a space before the caret and/or on the beginning of the next line.

**Comment by nabadger** [comment]
I'll close this for now as it's available on master. 

I'm working on some updates to documentation and a new release.
