### ISSUE TITLE
kubectl_version don't get from env variable

### ISSUE THREAD

**Issue by FreakyGranny** [mintel/dex-k8s-authenticator#85]
I setup config.yaml with env variable, but at result page kubectl download link look like 

`https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl `

my config:

```
clusters:
  ...
listen: http://0.0.0.0:5555
web_path_prefix: /
kubectl_version: ${KUBECTL_VERSION}
debug: true
```

**Comment by nickmintel** [comment]
Thanks - will have a look. Looks like kubectl_version is coming straight from `viper.String` (by-passing our built-in env-substitution). 

Will take a look soon.

**Comment by nabadger** [comment]
Should be fixed on `master` now. I'll prepare a new release soon.
